### ISSUE TITLE
Can't withdraw more than 7 hearts even when player as 10.

### ISSUE THREAD

**Issue by NopeProsOnly** [zrdzn/GreatLifeSteal#179]
![image](https://user-images.githubusercontent.com/78925970/225430980-6cea517a-6549-4209-aac3-10077a381270.png)

**Comment by zrdzn** [comment]
We have successfully resolved the issue on the Discord server, and it was found to be merely a configuration problem. Therefore, I am closing this issue as "won't fix" since no additional fixes are necessary.
