### ISSUE TITLE
Players Not Losing/Gaining Hearts After Kill

### ISSUE THREAD

**Issue by MaxwellRose101** [zrdzn/GreatLifeSteal#185]
Hello! The players on my server aren't losing or gaining hearts from a kill. I don't know why. Could someone help me?

**Comment by zrdzn** [comment]
Please upload your config.yml.

**Comment by MaxwellRose101** [comment]
[https://replit.com/@MaxwellRose1019/lifesteal#server/plugins/GreatLifeSteal/config.yml](url)

**Comment by zrdzn** [comment]
I've hidden your comment because you've linked your whole server directory along with some sensitive data, you probably should remove it immediately. Also, please use something lightweight like [Pastebin](https://pastebin.com/) or [Hastebin](https://www.toptal.com/developers/hastebin) because these websites don't take forever to load (at least for me).

**Comment by MaxwellRose101** [comment]
Ok!

**Comment by MaxwellRose101** [comment]
@zrdzn Here: [Pastebin Link](https://pastebin.com/6YV2ahLm

**Comment by zrdzn** [comment]
I also need you to send your latest.log from time when players don't receive their hearts, maybe are there any errors? Or some players have the same IP address?

**Comment by zrdzn** [comment]
All I see is unknown symbols, I need a clear log with properly formatted chars.

**Comment by MaxwellRose101** [comment]
Let me see if I can get that.

**Comment by MaxwellRose101** [comment]
I can't upload the entire log to pastebin. Should I just put it here in the comments?

**Comment by MaxwellRose101** [comment]
@zrdzn HELLO?

**Comment by zrdzn** [comment]
I couldn't reproduce that, there are no errors in the console, I tried it locally and it works for me, I have no idea what's wrong here - config also looks good to me. I asked earlier about ip of players, maybe try switching that option off in the config.

**Comment by MaxwellRose101** [comment]
Hmm. Ok.
