### ISSUE TITLE
The heart dissapears when I click on it after crafting

### ISSUE THREAD

**Issue by IceeFoox** [zrdzn/GreatLifeSteal#187]
I craft the heart.
Heart shows on crafting table.
I click on it to add it to my inventory.
It disappears. As if the game does not want me to have it.

**Comment by zrdzn** [comment]
What version do you us

**Comment by IceeFoox** [comment]
1.8.8

**Comment by IceeFoox** [comment]
https://github.com/IceeFoox/Heart-recipe

Here it is

**Comment by zrdzn** [comment]
Yeah it's happening on 1.8 version only I think, and only when all ingredients amounts are 1.

**Comment by zrdzn** [comment]
Duplicate #93

**Comment by IceeFoox** [comment]
So I guess 1.8 is bugged?

**Comment by zrdzn** [comment]
> So I guess 1.8 is bugged?

Whole crafting recipe management is a mess in older versions of API unfortunately. But there is an issue for that so maybe some day it will be fixed.

**Comment by zrdzn** [comment]
> So I guess 1.8 is bugged?

Whole crafting recipe management is a mess in older versions of API unfortunately. But there is an issue for that so maybe some day it will be fixed.

**Comment by IceeFoox** [comment]
Btw, it is not bugged like that when I leave the recipe to diamond blocks, and the middle of the table is glass. Its works normally with that recipe

**Comment by zrdzn** [comment]
I remember investigating that problem but I didn't find the solution at that time. It's especially weird because it doesn't happen on newer versions so I had problems with debugging it - I may look into that in near future though.

**Comment by IceeFoox** [comment]
ok, thank you.
