### ISSUE TITLE
Move to Okaeri-Configs

### ISSUE THREAD

**Issue by zrdzn** [zrdzn/GreatLifeSteal#197]

**Comment by ljacqu** [comment]
Hi, sorry for the intrusion :smile: Is there anything you were missing from ConfigMe? I guess having to get properties is a bit more annoying than a settings class whose values are just fully populated.

**Comment by zrdzn** [comment]
Hello! :smile: Personally, I have no objections to ConfigMe. I've been using this library for a long time and it helped me among other things, with migrations. However, recently I was doing a general code cleanup and came to the conclusion that keeping public static final fields in configuration classes doesn't fit the project's code style. So, I used a library that holds such values in POJO style. To be honest, I personally prefer the approach with multiple instances of classes over passing around a single instance of SettingsManager and retrieving static fields through it. Nevertheless, this doesn't decrease the capabilities of the ConfigMe library, which works very well, and I've never had any issues with it. :smile:

**Comment by ljacqu** [comment]
That makes a lot of sense! Thanks for the feedback, and for the kind words :blush::sparkles:
