### ISSUE TITLE
The Banning System

### ISSUE THREAD

**Issue by MaxwellRose101** [zrdzn/GreatLifeSteal#199]
For some reason, when I do /lifesteal lives announce MaxwellRose1019, it says its 8 hp when I have 10 hearts. Why is this? Also, when I get to 0 hp, it's supposed to perm-ban me. Why doesn't this happen?

**Comment by zrdzn** [comment]
1. It shows how many ho you can lose before provided action will execute some commands (min health)
2. You need to show me your config

**Comment by MaxwellRose101** [comment]
https://pastebin.com/9n378sEy

**Comment by zrdzn** [comment]
I heard from few people that `minimumHealth` set at 0 may not work, I'll leave that issue open for further investigations.

**Comment by MaxwellRose101** [comment]
Okay. Thanks for your help. :)

**Comment by zrdzn** [comment]
I have tried it on latest experimental build and it works fine - I've tested it mainly on 1.20.1. What plugin and server version did you use? Can you also try again with newest build too? You should backup your config though because there were some major changes.
