### ISSUE TITLE
Eliminate player from worlds, not the entire server

### ISSUE THREAD

**Issue by EditChris** [zrdzn/GreatLifeSteal#209]
For people that would want to have the LifeSteal worlds in the same server as other different worlds having the ability to, instead of just banning the player from the server, just ban the player from entering the LifeSteal worlds in any way would be a godsent.

All the other things in the plugin (except the crafting recipe for the heart item) can be enabled per world. Having this would really help.

**Comment by zrdzn** [comment]
Do you have any idea how could new config file look with these changes?
