### ISSUE TITLE
The Donation Button Does Not Work

### ISSUE THREAD

**Issue by isaacfonner** [zrdzn/GreatLifeSteal#229]
I wanted to donate for making such a cool plugin but the button does not work

**Comment by zrdzn** [comment]
I'm glad you like the plugin! You are correct, the old link doesn't seem to work anymore, so I've updated it to a new one [here](https://www.paypal.com/donate/?hosted_button_id=NSF2NFHK5ZV94). Thanks for your support! 🚀
